### ISSUE TITLE
Grade

### ISSUE THREAD

**Issue by eytanfb** [eytanfb/offtrafik#1]
Your Assignment v2 Submission Received 96 points. The following error(s) were encountered:
1. Scenarios - 2 points deducted
- Scenrio 3 failed when a null pointer was encountered. (-2 points)
1. Deductions - 2 points were deducted
- Runtime error encountered while running scenario . NullPointerException (-2 points)
  - w1: Unexpected exception caught in Agent thread:
  - java.lang.NullPointerException
    - at restaurant.gui.WaiterGui.DoGoToCook(WaiterGui.java:122)
    - at restaurant.WaiterAgent.sendOrderToCook(WaiterAgent.java:220)
    - at restaurant.WaiterAgent.pickAndExecuteAnAction(WaiterAgent.java:142)
    - at agent.Agent$AgentThread.run(Agent.java:137)

Comments: Be sure to put your design docs in a folder called docs. And remove the @Override annotations from your code. Careful with your print statements. For every customer the print is Done eating Steak = 1.

> Although you may be getting this message via email, it is an issue on issue on your private GitHub repository and you should interact with it on GitHub
> 
> Any and all discussions pertaining to this deduction **must** be done via comments on this issue. If you are statisfied with the grading, you **must** close the issue. Note that a closed issue implicitly signals that you do not want to discuss this any further. No emails are accepted.
> 
> You have until Oct 9th, 2013 to dispute this deduction. Please allow up to 72 hours for a response to a regrade request. You are expected to follow the _Grading Disputes_ policies outlined in the [course syllabus](http://www-scf.usc.edu/~csci201/syllabus.html).

**Comment by eytanfb** [comment]
Your Assignment v2 Submission Received 96 points. The following error(s) were encountered:
1. Scenarios - 2 points deducted
- Scenrio 3 failed when a null pointer was encountered. (-2 points)
1. Deductions - 2 points were deducted
- Runtime error encountered while running scenario . NullPointerException (-2 points)
  - w1: Unexpected exception caught in Agent thread:
  - java.lang.NullPointerException
    - at restaurant.gui.WaiterGui.DoGoToCook(WaiterGui.java:122)
    - at restaurant.WaiterAgent.sendOrderToCook(WaiterAgent.java:220)
    - at restaurant.WaiterAgent.pickAndExecuteAnAction(WaiterAgent.java:142)
    - at agent.Agent$AgentThread.run(Agent.java:137)

Comments: Be sure to put your design docs in a folder called docs. And remove the @Override annotations from your code. Careful with your print statements. For every customer the print is Done eating Steak = 1.

> Although you may be getting this message via email, it is an issue on issue on your private GitHub repository and you should interact with it on GitHub
> 
> Any and all discussions pertaining to this deduction **must** be done via comments on this issue. If you are statisfied with the grading, you **must** close the issue. Note that a closed issue implicitly signals that you do not want to discuss this any further. No emails are accepted.
> 
> You have until Oct 9th, 2013 to dispute this deduction. Please allow up to 72 hours for a response to a regrade request. You are expected to follow the _Grading Disputes_ policies outlined in the [course syllabus](http://www-scf.usc.edu/~csci201/syllabus.html).

**Comment by eytanfb** [comment]
Your Assignment v2 Submission Received 96 points. The following error(s) were encountered:
1. Scenarios - 2 points deducted
- Scenrio 3 failed when a null pointer was encountered. (-2 points)
1. Deductions - 2 points were deducted
- Runtime error encountered while running scenario . NullPointerException (-2 points)
  - w1: Unexpected exception caught in Agent thread:
  - java.lang.NullPointerException
    - at restaurant.gui.WaiterGui.DoGoToCook(WaiterGui.java:122)
    - at restaurant.WaiterAgent.sendOrderToCook(WaiterAgent.java:220)
    - at restaurant.WaiterAgent.pickAndExecuteAnAction(WaiterAgent.java:142)
    - at agent.Agent$AgentThread.run(Agent.java:137)

Comments: Be sure to put your design docs in a folder called docs. And remove the @Override annotations from your code. Careful with your print statements. For every customer the print is Done eating Steak = 1.

> Although you may be getting this message via email, it is an issue on issue on your private GitHub repository and you should interact with it on GitHub
> 
> Any and all discussions pertaining to this deduction **must** be done via comments on this issue. If you are statisfied with the grading, you **must** close the issue. Note that a closed issue implicitly signals that you do not want to discuss this any further. No emails are accepted.
> 
> You have until Oct 9th, 2013 to dispute this deduction. Please allow up to 72 hours for a response to a regrade request. You are expected to follow the _Grading Disputes_ policies outlined in the [course syllabus](http://www-scf.usc.edu/~csci201/syllabus.html).

**Comment by eytanfb** [comment]
Your Assignment v2 Submission Received 96 points. The following error(s) were encountered:
1. Scenarios - 2 points deducted
   - Scenrio 3 failed when a null pointer was encountered. (-2 points)
2. Deductions - 2 points were deducted
   - Runtime error encountered while running scenario. NullPointerException (-2 points)
     - w1: Unexpected exception caught in Agent thread:
     - java.lang.NullPointerException
     - at restaurant.gui.WaiterGui.DoGoToCook(WaiterGui.java:122)
     - at restaurant.WaiterAgent.sendOrderToCook(WaiterAgent.java:220)
     - at restaurant.WaiterAgent.pickAndExecuteAnAction(WaiterAgent.java:142)
     - at agent.Agent$AgentThread.run(Agent.java:137)

> Although you may be getting this message via email, it is an issue on issue on your private GitHub repository and you should interact with it on GitHub
> 
> Any and all discussions pertaining to this deduction **must** be done via comments on this issue. If you are statisfied with the grading, you **must** close the issue. Note that a closed issue implicitly signals that you do not want to discuss this any further. No emails are accepted.
> 
> You have until Oct 9th, 2013 to dispute this deduction. Please allow up to 72 hours for a response to a regrade request. You are expected to follow the _Grading Disputes_ policies outlined in the [course syllabus](http://www-scf.usc.edu/~csci201/syllabus.html).
